%YAML:1.0

# OVVU
imu0:
  T_i_b: # rotation from body to IMU R_BtoI, position of body in IMU p_BinI
    - [1.0, 0.0, 0.0, -0.136]
    - [0.0, 1.0, 0.0, -0.008]
    - [0.0, 0.0, 1.0, -0.564]
    - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 5.8860e-3  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 1.0000e-4    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyroscope_noise_density: 1.7453e-04     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk: 1.0000e-05       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  model: calibrated
  rostopic: /imu0
  time_offset: 0.0
  update_rate: 100.0